In [21]:
# Importing necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

In [22]:
df = pd.read_csv('boston.csv')
df.head()

CRIM     ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        B  LSTAT  PRICE  
0  396.90   4.98   24.0  
1  396.90   9.14   21.6  
2  392.83   4.03   34.7  
3  394.63   2.94   33.4  
4  396.90   5.33   36.2

In [23]:
df.shape

(506, 14)

In [24]:
df.describe()

CRIM           ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT       PRICE  
count  506.000000  506.000000  
mean    12.653063   22.532806  
std      7.141062    9.197104  
min      1.730000    5.000000  
25%      6.950000   17.025000  
50%     11.360000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

In [25]:
df.isnull().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
PRICE      0
dtype: int64

In [26]:
df.columns

Index(['CRIM ', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT', 'PRICE'],
      dtype='object')

In [27]:
X = df.drop('PRICE', axis=1)
y = df['PRICE']

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [29]:
lr_model = LinearRegression()
lr_model.fit(X_train, y_train)

LinearRegression()

In [30]:
lr_pred = lr_model.predict(X_test)
lr_pred

array([28.99672362, 36.02556534, 14.81694405, 25.03197915, 18.76987992,
       23.25442929, 17.66253818, 14.34119   , 23.01320703, 20.63245597,
       24.90850512, 18.63883645, -6.08842184, 21.75834668, 19.23922576,
       26.19319733, 20.64773313,  5.79472718, 40.50033966, 17.61289074,
       27.24909479, 30.06625441, 11.34179277, 24.16077616, 17.86058499,
       15.83609765, 22.78148106, 14.57704449, 22.43626052, 19.19631835,
       22.43383455, 25.21979081, 25.93909562, 17.70162434, 16.76911711,
       16.95125411, 31.23340153, 20.13246729, 23.76579011, 24.6322925 ,
       13.94204955, 32.25576301, 42.67251161, 17.32745046, 27.27618614,
       16.99310991, 14.07009109, 25.90341861, 20.29485982, 29.95339638,
       21.28860173, 34.34451856, 16.04739105, 26.22562412, 39.53939798,
       22.57950697, 18.84531367, 32.72531661, 25.0673037 , 12.88628956,
       22.68221908, 30.48287757, 31.52626806, 15.90148607, 20.22094826,
       16.71089812, 20.52384893, 25.96356264, 30.61607978, 11.59

In [31]:
lr_mse = mean_squared_error(y_test, lr_pred)
lr_mse

24.291119474973538

In [32]:
lr_r2 = r2_score(y_test, lr_pred)
lr_r2

0.6687594935356317

In [33]:
dtr_model = DecisionTreeRegressor()
dtr_model.fit(X_train, y_train)

DecisionTreeRegressor()

In [34]:
dtr_pred = dtr_model.predict(X_test)
dtr_pred

array([24.5, 32. , 15.2, 21.7, 23.2, 18.5, 16.6, 16.7, 22.7, 22. , 21.4,
       21.4,  7.4, 20.5, 19. , 25. , 18.8, 10.5, 44. , 16.7, 23.1, 24.4,
       12.5, 23.8, 13.8, 11.7, 21. , 13.5, 19.4, 20.8, 19.5, 23.1, 17.8,
       15. , 12.5, 15.6, 33.4, 18.5, 21.7, 24.6, 19.8, 28.4, 44. , 16.1,
       22. , 16.7, 14.3, 23.7, 17.7, 35.1, 19.4, 34.9, 16.7, 32. , 43.1,
       19.5, 15.2, 27.9, 22. , 23.1, 24.8, 33.4, 29.4, 16.1, 26.6, 14.4,
       15.4, 22.9, 27.9, 13.2, 21.8, 28.7,  8.3, 18.6, 21.4, 10.5, 19.3,
       50. , 13.3,  8.1, 21.2, 11.9, 19.4, 10.5, 16.2, 30.1, 13.9, 23. ,
       22.9, 18. , 23.3,  8.8, 19.2, 17.5, 15. , 19.3, 50. , 11.9, 11.7,
       10.2, 19. , 25. ])

In [35]:
dtr_mse = mean_squared_error(y_test, dtr_pred)
dtr_r2 = r2_score(y_test, dtr_pred)
print(dtr_mse)
print(dtr_r2)

10.72372549019608
0.8537682766651793


In [36]:
rfr_model = RandomForestRegressor()
rfr_model.fit(X_train, y_train)

RandomForestRegressor()

In [37]:
rfr_pred = rfr_model.predict(X_test)
rfr_pred

array([22.865, 30.827, 16.945, 23.895, 16.611, 21.13 , 18.72 , 16.379,
       21.172, 21.033, 20.601, 20.614,  9.202, 21.204, 19.251, 25.955,
       18.748,  8.547, 45.265, 14.834, 24.511, 23.75 , 14.505, 24.29 ,
       14.696, 14.637, 21.53 , 14.111, 19.527, 21.116, 20.066, 23.249,
       29.286, 20.356, 14.231, 15.95 , 34.777, 19.297, 21.051, 24.188,
       19.202, 30.046, 45.468, 19.122, 22.369, 13.504, 15.068, 24.386,
       17.846, 27.834, 21.192, 33.947, 16.473, 26.274, 45.656, 22.204,
       15.246, 32.445, 22.012, 20.564, 25.826, 33.811, 28.532, 18.643,
       27.179, 17.356, 13.549, 23.003, 28.49 , 15.95 , 20.682, 28.342,
       10.256, 21.939, 21.74 ,  7.062, 20.263, 45.893, 11.03 , 12.908,
       21.468, 12.875, 19.866,  8.865, 20.617, 26.684, 15.368, 23.269,
       23.549, 18.132, 22.142,  8.018, 19.571, 18.782, 22.682, 19.758,
       37.626, 12.605, 12.746, 12.841, 20.54 , 23.349])

In [38]:
rfr_mse = mean_squared_error(y_test, rfr_pred)
rfr_r2 = r2_score(y_test, rfr_pred)
print(rfr_mse)
print(rfr_r2)

9.057294186274513
0.8764922005118244


In [39]:
def model_evaluate(X, y):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    models = {
        'Linear Regression': LinearRegression(),
        'Decision Tree Regressor': DecisionTreeRegressor(),
        'Random Forest Regressor': RandomForestRegressor()
    }
    results = {}
    for name, model in models.items():
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        mse = mean_squared_error(y_test, y_pred)
        r2 = r2_score(y_test, y_pred)

        results[name] = {
            'MSE': mse,
            'R Squared': r2
        }
    return results

In [40]:
model_evaluate(X, y)

{'Linear Regression': {'MSE': 24.291119474973538,
  'R Squared': 0.6687594935356317},
 'Decision Tree Regressor': {'MSE': 23.11598039215686,
  'R Squared': 0.6847840190977124},
 'Random Forest Regressor': {'MSE': 8.128316539215675,
  'R Squared': 0.8891599998128356}}